{% set name = "pyincore-data" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
 
source:
  path: ../
  # This can be changed based on the local path
  #url: {{ name }}-{{ version }}.tar.gz
  #md5: {{ hash_value }}
 
build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv . " # verbose
  skip: True  # [py<36]
 
requirements:
  build:
    - python>=3.9
    - pip
    - numpy>=1.26.0,<2.0a0
 
  host:
    - python>=3.9
    - pip
    - numpy>=1.26.0,<2.0a0
     
  run:
    - python>=3.9
    - pyincore>=1.20.0
    - {{ pin_compatible('numpy') }}
    - folium>=0.11.0
    - pandas>=2.1.2
    - geopandas>=0.14.0
    - ipyleaflet>=0.16.0
    - branca>=0.3.0
    - sqlalchemy>=1.4.42
    - geojson>=2.5.0
    - python-dotenv>=0.19.0
    - beautifulsoup4>=4.12.2
    - pycodestyle>=2.10.0
    - requests>=2.31.0
    - setuptools>=65.5.0
    - fiona>=1.9.5
 
test:
  # Python imports
  imports:
    - pandas
   
  requires:
    # Put any additional test requirements here.  For example
    - pytest>=3.9
  commands:
    # You can put built-in test commands to be run here.  Use this to test that the entry points work.
     python -c "import pyincore_data; print('SUCCESS')" #; pyincore.test_client()"
    # You can also put a file called run_test.py in the recipe that will be run at test time.
 
about:
  home: https://tools.in-core.org
  license: MPL-2.0
  summary: 'Python library for data manipulation and handling of pyIncore'
  description: 'pyincore-data is a Python project that provides utilities for manipulating and handling for use with
  pyincore'
  dev_url: https://github.com/IN-CORE/pyincore-data
  doc_url: https://tools.in-core.org/doc/incore
