name: base
channels:
  - conda-forge
  - in-core
  - in-core/label/rc
dependencies:
  - python=3.8
  - Fiona>=1.8.13
  - GDAL>=3.0.4
  - numpy>=1.16.0
  - folium>=0.11.0
  - pandas>=1.2.5
  - geopandas>=0.8.1
  - pytest>=3.9.0
  - ipyleaflet>=0.13.4
  - branca>=0.3.1
