name: base
channels:
  - conda-forge
  - in-core
  - in-core/label/rc
dependencies:
  - python=3.8
  - GDAL>=3.3.1
  - numpy>=1.16.0
  - pytest>=3.9.0
  - pip
  - pip:
      - -r requirements.txt
      - -e .