name: pyincore_data
channels:
  - conda-forge
  - defaults
  - in-core
  - in-core/label/rc
dependencies:
  - python=3.8
  - folium>=0.11.0
  - pyincore>=1.7.0
    ipyleaflet>=0.16.0
    branca>=0.3.1
