name: base
channels:
  - conda-forge
  - in-core
  - in-core/label/rc
dependencies:
  - python=3.8
  - fiona>=1.8.21
  - numpy>=1.16.0
  - folium>=0.11.0
  - pandas>=0.24.1
  - geopandas>=0.6.1
  - pytest>=3.9.0
  - ipyleaflet>=0.13.4,<0.13.7
  - branca>=0.3.0
