name: pyincore_data
channels:
  - conda-forge
  - defaults
  - in-core
  - in-core/label/rc
dependencies:
  - python=3.8
  - pyincore>=1.7.0
  - numpy>=1.16.0
  - pandas>=0.24.1
  - folium>=0.11.0
  - geopandas>=0.6.1
  - ipyleaflet>=0.16.0
  - branca>=0.3.1
  - pytest>=3.9.0
