name: PYTEST

on:
  push:

env:
  MAIN_REPO: IN-CORE/pyincore-data

jobs:

  #-----------------------------------------------------------------------
  # UNIT TEST
  # ----------------------------------------------------------------------
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          $CONDA/bin/conda env update --file environment.yaml --name base
      - name: Run tests with pytest
        run: |
          echo "${{secrets.PYTEST_USER_TOKEN}}" > tests/pyincore_data/.incorepw
          $CONDA/bin/pytest --cache-clear -s tests/pyincore_data/test_pyincore_data.py --junitxml=test-reports/results.xml
