name: Release

on:
  push:
    branches:
      - main

  pull_request:

env:
  MAIN_REPO: IN-CORE/pyincore-data

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get release info
        id: release_info
        run: |
          version=$(awk -F= '/^release/ { print $2}' docs/source/conf.py | sed "s/[ ']//g")
          changelog="$(sed -e "1,/^## \[${version}\]/d" -e "/^## \[/,\$d" -e '/^$/d' CHANGELOG.md)"
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=version::$version"
          echo "::set-output name=changelog::$changelog"

      - name: create release
        if: github.event_name != 'pull_request' && github.repository == env.MAIN_REPO
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          tag_name: ${{ steps.release_info.outputs.version }}
          name: Release ${{ steps.release_info.outputs.version }}
          body: ${{ steps.release_info.outputs.changelog }}
